Add macOS buildandpack with signing
microsoft/go pull request #1388
Opened 2024-11-05 00:06 UTC by dagood

* Add macOS builds.
  * Based on https://github.com/microsoft/go/pull/1279
* Rework signing to support macOS hardening and notarization.
  * Support multiple signing passes, needed for macOS artifacts in particular.
  * No more complex MSBuild logic. Now written in Go.
  * Create .sig files for Windows. We can do this now that we have multiple passes.
  * Add parameter to sign existing build for faster dev iteration.
* For https://github.com/microsoft/go/issues/1368

Notarization isn't working yet, pending https://portal.microsofticm.com/imp/v5/incidents/details/560612351/summary. For now, this PR skips that step.

Test end-to-end build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2575069&view=results
More recent test signing an existing build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2575146&view=results
(I've done a little code polishing since the first build.)

2024-11-05 17:44 UTC, dagood commented on eng/_util/cmd/sign/archive.go
> +		}
The AI suggestion is no good, but this is indeed something to fix.

2024-11-06 06:11 UTC, gdams approved these changes

2024-11-06 06:13 UTC, qmuntal requested changes
Done a first pass review. Overall looks great.

2024-11-06 06:13 UTC, qmuntal commented on eng/_util/cmd/sign/archiveutil.go
> +func eachZipEntry(r *zip.ReadCloser, f func(*zip.File) error) error {
The "each*" functions can be rewritten into iterators. They calling site would look a bit nicer and less magic.

2024-11-06 06:13 UTC, qmuntal commented on eng/_util/cmd/sign/archiveutil.go
> +func firstError(errs ...error) error {
Since Go 1.22 this pattern is generically implemented in the standard library by [cmp.Or](https://pkg.go.dev/cmp#Or). I think it can replace `firstError`.

2024-11-06 06:13 UTC, qmuntal commented on eng/_util/cmd/sign/sign.go
> +		if existingF, ok := archiveFilenames[filepath.Base(f)]; ok {
This does a case sensitive check, but some OSes are case insensitive (e.g. Windows). We should at least convert the file name to lower case before checking and adding file names to the map.

2024-11-06 18:15 UTC, dagood commented on eng/_util/cmd/sign/archiveutil.go
> +func eachZipEntry(r *zip.ReadCloser, f func(*zip.File) error) error {
I'm curious what you think about handling errors in iterators. My first impression is that `for v, err := range eachZipEntry(...)` is odd, but it's the solution I'd go with. It does look like this is popping up in the wild.

---

Other factor: our bootstrap is still 1.22, and range func is new to 1.23. (I did initially dabble with an iterator but this stopped me early on.)

Also, if we decide to move this code to go-infra, we'd have to upgrade that module from 1.22 to 1.23. (But we could just wait until 1.24 releases and do it then--if we even have a reason to. I don't anticipate e.g. moving signing into the release pipelines.)

---

Personally, I think the callbacks are just fine. A downside is that you can't interrupt them (without returning an error value) but this code doesn't need to do that. This is certainly down to my background and whims, though. 😄

2024-11-06 18:15 UTC, dagood commented on eng/_util/cmd/sign/archiveutil.go
> +func firstError(errs ...error) error {
Neat! I glanced at `slices` for something like that, missed that one. Odd name but it's an exact fit.

2024-11-07 17:16 UTC, qmuntal commented on eng/_util/cmd/sign/archiveutil.go
> +func eachZipEntry(r *zip.ReadCloser, f func(*zip.File) error) error {
You convinced me. `each*` is fine :)

2024-11-07 17:17 UTC, qmuntal approved these changes

2024-11-07 19:00 UTC, merged